<?php
/**
 * OfficesApi
 * PHP version 7.3
 *
 * @category Class
 * @package  NorthernEstateAgencies\ReapitFoundationsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Foundations Interactive API Explorer
 *
 * <p>Technical documentation for the Reapit Foundations REST API endpoints. This tool is interactive and provides instant access to data hosted in our <strong><a href=\"https://foundations-documentation.reapit.cloud/api/api-documentation#sandbox-mode\">sandbox environment</a> </strong>with <strong>authentication</strong> and <strong>versioning</strong> headers pre-populated. Example requests and responses are shown by default but you can switch to view a fully documented schema - look for the&nbsp;<strong>model</strong> link.</p> <p>* To begin developing with the platform, consult our&nbsp;<strong><a href=\"https://foundations-documentation.reapit.cloud/api/api-documentation\">documentation</a></strong>&nbsp;<br />* To report a bug or request a new feature, see our <strong><a href=\"https://developers.reapit.cloud/help\">help pages</a>&nbsp;<br /></strong>* For information on terminology, see our&nbsp;<strong><a href=\"https://foundations-documentation.reapit.cloud/platform-glossary\">glossary</a></strong>&nbsp;<br />* Our APIs are located at&nbsp;<strong>https://platform.reapit.cloud<br /></strong>* The current API version is&nbsp;<strong>2020-01-31<br /></strong></p>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NorthernEstateAgencies\ReapitFoundationsClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use NorthernEstateAgencies\ReapitFoundationsClient\ApiException;
use NorthernEstateAgencies\ReapitFoundationsClient\Configuration;
use NorthernEstateAgencies\ReapitFoundationsClient\HeaderSelector;
use NorthernEstateAgencies\ReapitFoundationsClient\ObjectSerializer;

/**
 * OfficesApi Class Doc Comment
 *
 * @category Class
 * @package  NorthernEstateAgencies\ReapitFoundationsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OfficesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getOfficeById
     *
     * Gets a specific office by unique identifier
     *
     * @param  string $id The unique identifier of the office (required)
     * @param  string[] $embed Embed additional resources into the office returned (optional)
     * @param  string[] $extrasField Include extras fields matching one or more field names specified. You must be granted access to this data beforehand (optional)
     *
     * @throws \NorthernEstateAgencies\ReapitFoundationsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20026Embedded
     */
    public function getOfficeById($id, $embed = null, $extrasField = null)
    {
        list($response) = $this->getOfficeByIdWithHttpInfo($id, $embed, $extrasField);
        return $response;
    }

    /**
     * Operation getOfficeByIdWithHttpInfo
     *
     * Gets a specific office by unique identifier
     *
     * @param  string $id The unique identifier of the office (required)
     * @param  string[] $embed Embed additional resources into the office returned (optional)
     * @param  string[] $extrasField Include extras fields matching one or more field names specified. You must be granted access to this data beforehand (optional)
     *
     * @throws \NorthernEstateAgencies\ReapitFoundationsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20026Embedded, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOfficeByIdWithHttpInfo($id, $embed = null, $extrasField = null)
    {
        $request = $this->getOfficeByIdRequest($id, $embed, $extrasField);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20026Embedded' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20026Embedded', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20026Embedded';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20026Embedded',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getOfficeByIdAsync
     *
     * Gets a specific office by unique identifier
     *
     * @param  string $id The unique identifier of the office (required)
     * @param  string[] $embed Embed additional resources into the office returned (optional)
     * @param  string[] $extrasField Include extras fields matching one or more field names specified. You must be granted access to this data beforehand (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOfficeByIdAsync($id, $embed = null, $extrasField = null)
    {
        return $this->getOfficeByIdAsyncWithHttpInfo($id, $embed, $extrasField)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOfficeByIdAsyncWithHttpInfo
     *
     * Gets a specific office by unique identifier
     *
     * @param  string $id The unique identifier of the office (required)
     * @param  string[] $embed Embed additional resources into the office returned (optional)
     * @param  string[] $extrasField Include extras fields matching one or more field names specified. You must be granted access to this data beforehand (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOfficeByIdAsyncWithHttpInfo($id, $embed = null, $extrasField = null)
    {
        $returnType = '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20026Embedded';
        $request = $this->getOfficeByIdRequest($id, $embed, $extrasField);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOfficeById'
     *
     * @param  string $id The unique identifier of the office (required)
     * @param  string[] $embed Embed additional resources into the office returned (optional)
     * @param  string[] $extrasField Include extras fields matching one or more field names specified. You must be granted access to this data beforehand (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getOfficeByIdRequest($id, $embed = null, $extrasField = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getOfficeById'
            );
        }



        $resourcePath = '/offices/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($embed !== null) {
            if('form' === 'form' && is_array($embed)) {
                foreach($embed as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['embed'] = $embed;
            }
        }
        // query params
        if ($extrasField !== null) {
            if('form' === 'form' && is_array($extrasField)) {
                foreach($extrasField as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['extrasField'] = $extrasField;
            }
        }


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation officesGet
     *
     * Gets a collection of offices matching the filter criteria provided
     *
     * @param  int $pageSize A limit on the number of offices to be returned per page. Value can range between 1 and 100, and the default is 25 (optional)
     * @param  int $pageNumber The page number to return (must be greater than 0) (optional)
     * @param  string $sortBy Sort results by the value specified. Prefix string with &#39;-&#39; to indicate descending direction (created/modified/name/address) (optional)
     * @param  string[] $embed Embed additional resources into the offices returned (optional)
     * @param  string[] $id id (optional)
     * @param  string $address address (optional)
     * @param  string $name name (optional)
     * @param  \DateTime $createdFrom Only return offices where the &#x60;created&#x60; field is on or after the ISO8601 date and time value provided (optional)
     * @param  \DateTime $createdTo Only return offices where the &#x60;created&#x60; field is on or before the ISO8601 date and time value provided (optional)
     * @param  \DateTime $modifiedFrom Only return offices where the &#x60;modified&#x60; field is on or after the ISO8601 date and time value provided (optional)
     * @param  \DateTime $modifiedTo Only return offices where the &#x60;modified&#x60; field is on or before the ISO8601 date and time value provided (optional)
     * @param  string[] $metadata Only return offices where the metadata matches the filters given (optional)
     * @param  string[] $extrasField Include extras fields matching one or more field names specified. You must be granted access to this data beforehand (optional)
     *
     * @throws \NorthernEstateAgencies\ReapitFoundationsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20026
     */
    public function officesGet($pageSize = null, $pageNumber = null, $sortBy = null, $embed = null, $id = null, $address = null, $name = null, $createdFrom = null, $createdTo = null, $modifiedFrom = null, $modifiedTo = null, $metadata = null, $extrasField = null)
    {
        list($response) = $this->officesGetWithHttpInfo($pageSize, $pageNumber, $sortBy, $embed, $id, $address, $name, $createdFrom, $createdTo, $modifiedFrom, $modifiedTo, $metadata, $extrasField);
        return $response;
    }

    /**
     * Operation officesGetWithHttpInfo
     *
     * Gets a collection of offices matching the filter criteria provided
     *
     * @param  int $pageSize A limit on the number of offices to be returned per page. Value can range between 1 and 100, and the default is 25 (optional)
     * @param  int $pageNumber The page number to return (must be greater than 0) (optional)
     * @param  string $sortBy Sort results by the value specified. Prefix string with &#39;-&#39; to indicate descending direction (created/modified/name/address) (optional)
     * @param  string[] $embed Embed additional resources into the offices returned (optional)
     * @param  string[] $id (optional)
     * @param  string $address (optional)
     * @param  string $name (optional)
     * @param  \DateTime $createdFrom Only return offices where the &#x60;created&#x60; field is on or after the ISO8601 date and time value provided (optional)
     * @param  \DateTime $createdTo Only return offices where the &#x60;created&#x60; field is on or before the ISO8601 date and time value provided (optional)
     * @param  \DateTime $modifiedFrom Only return offices where the &#x60;modified&#x60; field is on or after the ISO8601 date and time value provided (optional)
     * @param  \DateTime $modifiedTo Only return offices where the &#x60;modified&#x60; field is on or before the ISO8601 date and time value provided (optional)
     * @param  string[] $metadata Only return offices where the metadata matches the filters given (optional)
     * @param  string[] $extrasField Include extras fields matching one or more field names specified. You must be granted access to this data beforehand (optional)
     *
     * @throws \NorthernEstateAgencies\ReapitFoundationsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20026, HTTP status code, HTTP response headers (array of strings)
     */
    public function officesGetWithHttpInfo($pageSize = null, $pageNumber = null, $sortBy = null, $embed = null, $id = null, $address = null, $name = null, $createdFrom = null, $createdTo = null, $modifiedFrom = null, $modifiedTo = null, $metadata = null, $extrasField = null)
    {
        $request = $this->officesGetRequest($pageSize, $pageNumber, $sortBy, $embed, $id, $address, $name, $createdFrom, $createdTo, $modifiedFrom, $modifiedTo, $metadata, $extrasField);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20026' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20026', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20026';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20026',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation officesGetAsync
     *
     * Gets a collection of offices matching the filter criteria provided
     *
     * @param  int $pageSize A limit on the number of offices to be returned per page. Value can range between 1 and 100, and the default is 25 (optional)
     * @param  int $pageNumber The page number to return (must be greater than 0) (optional)
     * @param  string $sortBy Sort results by the value specified. Prefix string with &#39;-&#39; to indicate descending direction (created/modified/name/address) (optional)
     * @param  string[] $embed Embed additional resources into the offices returned (optional)
     * @param  string[] $id (optional)
     * @param  string $address (optional)
     * @param  string $name (optional)
     * @param  \DateTime $createdFrom Only return offices where the &#x60;created&#x60; field is on or after the ISO8601 date and time value provided (optional)
     * @param  \DateTime $createdTo Only return offices where the &#x60;created&#x60; field is on or before the ISO8601 date and time value provided (optional)
     * @param  \DateTime $modifiedFrom Only return offices where the &#x60;modified&#x60; field is on or after the ISO8601 date and time value provided (optional)
     * @param  \DateTime $modifiedTo Only return offices where the &#x60;modified&#x60; field is on or before the ISO8601 date and time value provided (optional)
     * @param  string[] $metadata Only return offices where the metadata matches the filters given (optional)
     * @param  string[] $extrasField Include extras fields matching one or more field names specified. You must be granted access to this data beforehand (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function officesGetAsync($pageSize = null, $pageNumber = null, $sortBy = null, $embed = null, $id = null, $address = null, $name = null, $createdFrom = null, $createdTo = null, $modifiedFrom = null, $modifiedTo = null, $metadata = null, $extrasField = null)
    {
        return $this->officesGetAsyncWithHttpInfo($pageSize, $pageNumber, $sortBy, $embed, $id, $address, $name, $createdFrom, $createdTo, $modifiedFrom, $modifiedTo, $metadata, $extrasField)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation officesGetAsyncWithHttpInfo
     *
     * Gets a collection of offices matching the filter criteria provided
     *
     * @param  int $pageSize A limit on the number of offices to be returned per page. Value can range between 1 and 100, and the default is 25 (optional)
     * @param  int $pageNumber The page number to return (must be greater than 0) (optional)
     * @param  string $sortBy Sort results by the value specified. Prefix string with &#39;-&#39; to indicate descending direction (created/modified/name/address) (optional)
     * @param  string[] $embed Embed additional resources into the offices returned (optional)
     * @param  string[] $id (optional)
     * @param  string $address (optional)
     * @param  string $name (optional)
     * @param  \DateTime $createdFrom Only return offices where the &#x60;created&#x60; field is on or after the ISO8601 date and time value provided (optional)
     * @param  \DateTime $createdTo Only return offices where the &#x60;created&#x60; field is on or before the ISO8601 date and time value provided (optional)
     * @param  \DateTime $modifiedFrom Only return offices where the &#x60;modified&#x60; field is on or after the ISO8601 date and time value provided (optional)
     * @param  \DateTime $modifiedTo Only return offices where the &#x60;modified&#x60; field is on or before the ISO8601 date and time value provided (optional)
     * @param  string[] $metadata Only return offices where the metadata matches the filters given (optional)
     * @param  string[] $extrasField Include extras fields matching one or more field names specified. You must be granted access to this data beforehand (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function officesGetAsyncWithHttpInfo($pageSize = null, $pageNumber = null, $sortBy = null, $embed = null, $id = null, $address = null, $name = null, $createdFrom = null, $createdTo = null, $modifiedFrom = null, $modifiedTo = null, $metadata = null, $extrasField = null)
    {
        $returnType = '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20026';
        $request = $this->officesGetRequest($pageSize, $pageNumber, $sortBy, $embed, $id, $address, $name, $createdFrom, $createdTo, $modifiedFrom, $modifiedTo, $metadata, $extrasField);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'officesGet'
     *
     * @param  int $pageSize A limit on the number of offices to be returned per page. Value can range between 1 and 100, and the default is 25 (optional)
     * @param  int $pageNumber The page number to return (must be greater than 0) (optional)
     * @param  string $sortBy Sort results by the value specified. Prefix string with &#39;-&#39; to indicate descending direction (created/modified/name/address) (optional)
     * @param  string[] $embed Embed additional resources into the offices returned (optional)
     * @param  string[] $id (optional)
     * @param  string $address (optional)
     * @param  string $name (optional)
     * @param  \DateTime $createdFrom Only return offices where the &#x60;created&#x60; field is on or after the ISO8601 date and time value provided (optional)
     * @param  \DateTime $createdTo Only return offices where the &#x60;created&#x60; field is on or before the ISO8601 date and time value provided (optional)
     * @param  \DateTime $modifiedFrom Only return offices where the &#x60;modified&#x60; field is on or after the ISO8601 date and time value provided (optional)
     * @param  \DateTime $modifiedTo Only return offices where the &#x60;modified&#x60; field is on or before the ISO8601 date and time value provided (optional)
     * @param  string[] $metadata Only return offices where the metadata matches the filters given (optional)
     * @param  string[] $extrasField Include extras fields matching one or more field names specified. You must be granted access to this data beforehand (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function officesGetRequest($pageSize = null, $pageNumber = null, $sortBy = null, $embed = null, $id = null, $address = null, $name = null, $createdFrom = null, $createdTo = null, $modifiedFrom = null, $modifiedTo = null, $metadata = null, $extrasField = null)
    {





        $resourcePath = '/offices/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($pageSize)) {
            $pageSize = ObjectSerializer::serializeCollection($pageSize, '', true);
        }
        if ($pageSize !== null) {
            $queryParams['pageSize'] = $pageSize;
        }
        // query params
        if (is_array($pageNumber)) {
            $pageNumber = ObjectSerializer::serializeCollection($pageNumber, '', true);
        }
        if ($pageNumber !== null) {
            $queryParams['pageNumber'] = $pageNumber;
        }
        // query params
        if (is_array($sortBy)) {
            $sortBy = ObjectSerializer::serializeCollection($sortBy, '', true);
        }
        if ($sortBy !== null) {
            $queryParams['sortBy'] = $sortBy;
        }
        // query params
        if ($embed !== null) {
            if('form' === 'form' && is_array($embed)) {
                foreach($embed as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['embed'] = $embed;
            }
        }
        // query params
        if ($id !== null) {
            if('form' === 'form' && is_array($id)) {
                foreach($id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['id'] = $id;
            }
        }
        // query params
        if (is_array($address)) {
            $address = ObjectSerializer::serializeCollection($address, '', true);
        }
        if ($address !== null) {
            $queryParams['address'] = $address;
        }
        // query params
        if (is_array($name)) {
            $name = ObjectSerializer::serializeCollection($name, '', true);
        }
        if ($name !== null) {
            $queryParams['name'] = $name;
        }
        // query params
        if (is_array($createdFrom)) {
            $createdFrom = ObjectSerializer::serializeCollection($createdFrom, '', true);
        }
        if ($createdFrom !== null) {
            $queryParams['createdFrom'] = $createdFrom;
        }
        // query params
        if (is_array($createdTo)) {
            $createdTo = ObjectSerializer::serializeCollection($createdTo, '', true);
        }
        if ($createdTo !== null) {
            $queryParams['createdTo'] = $createdTo;
        }
        // query params
        if (is_array($modifiedFrom)) {
            $modifiedFrom = ObjectSerializer::serializeCollection($modifiedFrom, '', true);
        }
        if ($modifiedFrom !== null) {
            $queryParams['modifiedFrom'] = $modifiedFrom;
        }
        // query params
        if (is_array($modifiedTo)) {
            $modifiedTo = ObjectSerializer::serializeCollection($modifiedTo, '', true);
        }
        if ($modifiedTo !== null) {
            $queryParams['modifiedTo'] = $modifiedTo;
        }
        // query params
        if ($metadata !== null) {
            if('form' === 'form' && is_array($metadata)) {
                foreach($metadata as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['metadata'] = $metadata;
            }
        }
        // query params
        if ($extrasField !== null) {
            if('form' === 'form' && is_array($extrasField)) {
                foreach($extrasField as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['extrasField'] = $extrasField;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation officesIdPatch
     *
     * Updates an office by unique identifier
     *
     * @param  string $ifMatch The ETag provided in the payload from the current version of this resource (required)
     * @param  string $id The unique identifier of the office to update. (required)
     * @param  \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineObject35 $body body (optional)
     *
     * @throws \NorthernEstateAgencies\ReapitFoundationsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function officesIdPatch($ifMatch, $id, $body = null)
    {
        $this->officesIdPatchWithHttpInfo($ifMatch, $id, $body);
    }

    /**
     * Operation officesIdPatchWithHttpInfo
     *
     * Updates an office by unique identifier
     *
     * @param  string $ifMatch The ETag provided in the payload from the current version of this resource (required)
     * @param  string $id The unique identifier of the office to update. (required)
     * @param  \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineObject35 $body (optional)
     *
     * @throws \NorthernEstateAgencies\ReapitFoundationsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function officesIdPatchWithHttpInfo($ifMatch, $id, $body = null)
    {
        $request = $this->officesIdPatchRequest($ifMatch, $id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation officesIdPatchAsync
     *
     * Updates an office by unique identifier
     *
     * @param  string $ifMatch The ETag provided in the payload from the current version of this resource (required)
     * @param  string $id The unique identifier of the office to update. (required)
     * @param  \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineObject35 $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function officesIdPatchAsync($ifMatch, $id, $body = null)
    {
        return $this->officesIdPatchAsyncWithHttpInfo($ifMatch, $id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation officesIdPatchAsyncWithHttpInfo
     *
     * Updates an office by unique identifier
     *
     * @param  string $ifMatch The ETag provided in the payload from the current version of this resource (required)
     * @param  string $id The unique identifier of the office to update. (required)
     * @param  \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineObject35 $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function officesIdPatchAsyncWithHttpInfo($ifMatch, $id, $body = null)
    {
        $returnType = '';
        $request = $this->officesIdPatchRequest($ifMatch, $id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'officesIdPatch'
     *
     * @param  string $ifMatch The ETag provided in the payload from the current version of this resource (required)
     * @param  string $id The unique identifier of the office to update. (required)
     * @param  \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineObject35 $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function officesIdPatchRequest($ifMatch, $id, $body = null)
    {
        // verify the required parameter 'ifMatch' is set
        if ($ifMatch === null || (is_array($ifMatch) && count($ifMatch) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ifMatch when calling officesIdPatch'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling officesIdPatch'
            );
        }

        $resourcePath = '/offices/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($ifMatch !== null) {
            $headerParams['If-Match'] = ObjectSerializer::toHeaderValue($ifMatch);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                ['application/json-patch+json', 'application/json', 'application/_*+json']
            );
        }

        // for model (json/xml)
        if (isset($body)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation officesPost
     *
     * Creates a new office
     *
     * @param  \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineObject34 $body body (optional)
     *
     * @throws \NorthernEstateAgencies\ReapitFoundationsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function officesPost($body = null)
    {
        $this->officesPostWithHttpInfo($body);
    }

    /**
     * Operation officesPostWithHttpInfo
     *
     * Creates a new office
     *
     * @param  \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineObject34 $body (optional)
     *
     * @throws \NorthernEstateAgencies\ReapitFoundationsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function officesPostWithHttpInfo($body = null)
    {
        $request = $this->officesPostRequest($body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation officesPostAsync
     *
     * Creates a new office
     *
     * @param  \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineObject34 $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function officesPostAsync($body = null)
    {
        return $this->officesPostAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation officesPostAsyncWithHttpInfo
     *
     * Creates a new office
     *
     * @param  \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineObject34 $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function officesPostAsyncWithHttpInfo($body = null)
    {
        $returnType = '';
        $request = $this->officesPostRequest($body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'officesPost'
     *
     * @param  \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineObject34 $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function officesPostRequest($body = null)
    {

        $resourcePath = '/offices/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                ['application/json-patch+json', 'application/json', 'application/_*+json']
            );
        }

        // for model (json/xml)
        if (isset($body)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
