<?php
/**
 * TransactionsApi
 * PHP version 7.3
 *
 * @category Class
 * @package  NorthernEstateAgencies\ReapitFoundationsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Foundations Interactive API Explorer
 *
 * <p>Technical documentation for the Reapit Foundations REST API endpoints. This tool is interactive and provides instant access to data hosted in our <strong><a href=\"https://foundations-documentation.reapit.cloud/api/api-documentation#sandbox-mode\">sandbox environment</a> </strong>with <strong>authentication</strong> and <strong>versioning</strong> headers pre-populated. Example requests and responses are shown by default but you can switch to view a fully documented schema - look for the&nbsp;<strong>model</strong> link.</p> <p>* To begin developing with the platform, consult our&nbsp;<strong><a href=\"https://foundations-documentation.reapit.cloud/api/api-documentation\">documentation</a></strong>&nbsp;<br />* To report a bug or request a new feature, see our <strong><a href=\"https://developers.reapit.cloud/help\">help pages</a>&nbsp;<br /></strong>* For information on terminology, see our&nbsp;<strong><a href=\"https://foundations-documentation.reapit.cloud/platform-glossary\">glossary</a></strong>&nbsp;<br />* Our APIs are located at&nbsp;<strong>https://platform.reapit.cloud<br /></strong>* The current API version is&nbsp;<strong>2020-01-31<br /></strong></p>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NorthernEstateAgencies\ReapitFoundationsClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use NorthernEstateAgencies\ReapitFoundationsClient\ApiException;
use NorthernEstateAgencies\ReapitFoundationsClient\Configuration;
use NorthernEstateAgencies\ReapitFoundationsClient\HeaderSelector;
use NorthernEstateAgencies\ReapitFoundationsClient\ObjectSerializer;

/**
 * TransactionsApi Class Doc Comment
 *
 * @category Class
 * @package  NorthernEstateAgencies\ReapitFoundationsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransactionsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation transactionsGet
     *
     * Retrieves a collection of transactions
     *
     * @param  int $pageSize A limit on the number of transactions to be returned per page. Value can range between 1 and 100, and the default is 25 (optional)
     * @param  int $pageNumber The page number to return (optional)
     * @param  string $sortBy Sort results by the value specified. Prefix string with &#39;-&#39; to indicate descending direction (created/modified) (optional)
     * @param  string[] $id Only return transactions where the &#x60;id&#x60; field matches one or more values provided (optional)
     * @param  string[] $propertyId Only return transactions where the &#x60;propertyId&#x60; field matches one or more values provided (optional)
     * @param  string[] $landlordId Only return transactions where the &#x60;landlordId&#x60; field matches one or more values provided (optional)
     * @param  string[] $tenancyId Only return transactions where the &#x60;tenancyId&#x60; field matches one or more values provided (optional)
     * @param  string[] $status Only return transactions where the &#x60;status&#x60; field matches one or more values provided (optional)
     * @param  string[] $type Only return transactions where the &#x60;type&#x60; field matches one or more values provided (optional)
     * @param  string[] $ledger Only return transactions where the &#x60;ledger&#x60; field matches one or more values provided (optional)
     * @param  string[] $category Only return transactions where the &#x60;category&#x60; field matches one or more values provided (optional)
     * @param  \DateTime $createdFrom Only return transactions where the &#x60;created&#x60; field is on or after the ISO8601 date and time value provided (optional)
     * @param  \DateTime $createdTo Only return transactions where the &#x60;created&#x60; field is on or before the ISO8601 date and time value provided (optional)
     *
     * @throws \NorthernEstateAgencies\ReapitFoundationsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20036
     */
    public function transactionsGet($pageSize = null, $pageNumber = null, $sortBy = null, $id = null, $propertyId = null, $landlordId = null, $tenancyId = null, $status = null, $type = null, $ledger = null, $category = null, $createdFrom = null, $createdTo = null)
    {
        list($response) = $this->transactionsGetWithHttpInfo($pageSize, $pageNumber, $sortBy, $id, $propertyId, $landlordId, $tenancyId, $status, $type, $ledger, $category, $createdFrom, $createdTo);
        return $response;
    }

    /**
     * Operation transactionsGetWithHttpInfo
     *
     * Retrieves a collection of transactions
     *
     * @param  int $pageSize A limit on the number of transactions to be returned per page. Value can range between 1 and 100, and the default is 25 (optional)
     * @param  int $pageNumber The page number to return (optional)
     * @param  string $sortBy Sort results by the value specified. Prefix string with &#39;-&#39; to indicate descending direction (created/modified) (optional)
     * @param  string[] $id Only return transactions where the &#x60;id&#x60; field matches one or more values provided (optional)
     * @param  string[] $propertyId Only return transactions where the &#x60;propertyId&#x60; field matches one or more values provided (optional)
     * @param  string[] $landlordId Only return transactions where the &#x60;landlordId&#x60; field matches one or more values provided (optional)
     * @param  string[] $tenancyId Only return transactions where the &#x60;tenancyId&#x60; field matches one or more values provided (optional)
     * @param  string[] $status Only return transactions where the &#x60;status&#x60; field matches one or more values provided (optional)
     * @param  string[] $type Only return transactions where the &#x60;type&#x60; field matches one or more values provided (optional)
     * @param  string[] $ledger Only return transactions where the &#x60;ledger&#x60; field matches one or more values provided (optional)
     * @param  string[] $category Only return transactions where the &#x60;category&#x60; field matches one or more values provided (optional)
     * @param  \DateTime $createdFrom Only return transactions where the &#x60;created&#x60; field is on or after the ISO8601 date and time value provided (optional)
     * @param  \DateTime $createdTo Only return transactions where the &#x60;created&#x60; field is on or before the ISO8601 date and time value provided (optional)
     *
     * @throws \NorthernEstateAgencies\ReapitFoundationsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20036, HTTP status code, HTTP response headers (array of strings)
     */
    public function transactionsGetWithHttpInfo($pageSize = null, $pageNumber = null, $sortBy = null, $id = null, $propertyId = null, $landlordId = null, $tenancyId = null, $status = null, $type = null, $ledger = null, $category = null, $createdFrom = null, $createdTo = null)
    {
        $request = $this->transactionsGetRequest($pageSize, $pageNumber, $sortBy, $id, $propertyId, $landlordId, $tenancyId, $status, $type, $ledger, $category, $createdFrom, $createdTo);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20036' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20036', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20036';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20036',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation transactionsGetAsync
     *
     * Retrieves a collection of transactions
     *
     * @param  int $pageSize A limit on the number of transactions to be returned per page. Value can range between 1 and 100, and the default is 25 (optional)
     * @param  int $pageNumber The page number to return (optional)
     * @param  string $sortBy Sort results by the value specified. Prefix string with &#39;-&#39; to indicate descending direction (created/modified) (optional)
     * @param  string[] $id Only return transactions where the &#x60;id&#x60; field matches one or more values provided (optional)
     * @param  string[] $propertyId Only return transactions where the &#x60;propertyId&#x60; field matches one or more values provided (optional)
     * @param  string[] $landlordId Only return transactions where the &#x60;landlordId&#x60; field matches one or more values provided (optional)
     * @param  string[] $tenancyId Only return transactions where the &#x60;tenancyId&#x60; field matches one or more values provided (optional)
     * @param  string[] $status Only return transactions where the &#x60;status&#x60; field matches one or more values provided (optional)
     * @param  string[] $type Only return transactions where the &#x60;type&#x60; field matches one or more values provided (optional)
     * @param  string[] $ledger Only return transactions where the &#x60;ledger&#x60; field matches one or more values provided (optional)
     * @param  string[] $category Only return transactions where the &#x60;category&#x60; field matches one or more values provided (optional)
     * @param  \DateTime $createdFrom Only return transactions where the &#x60;created&#x60; field is on or after the ISO8601 date and time value provided (optional)
     * @param  \DateTime $createdTo Only return transactions where the &#x60;created&#x60; field is on or before the ISO8601 date and time value provided (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transactionsGetAsync($pageSize = null, $pageNumber = null, $sortBy = null, $id = null, $propertyId = null, $landlordId = null, $tenancyId = null, $status = null, $type = null, $ledger = null, $category = null, $createdFrom = null, $createdTo = null)
    {
        return $this->transactionsGetAsyncWithHttpInfo($pageSize, $pageNumber, $sortBy, $id, $propertyId, $landlordId, $tenancyId, $status, $type, $ledger, $category, $createdFrom, $createdTo)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation transactionsGetAsyncWithHttpInfo
     *
     * Retrieves a collection of transactions
     *
     * @param  int $pageSize A limit on the number of transactions to be returned per page. Value can range between 1 and 100, and the default is 25 (optional)
     * @param  int $pageNumber The page number to return (optional)
     * @param  string $sortBy Sort results by the value specified. Prefix string with &#39;-&#39; to indicate descending direction (created/modified) (optional)
     * @param  string[] $id Only return transactions where the &#x60;id&#x60; field matches one or more values provided (optional)
     * @param  string[] $propertyId Only return transactions where the &#x60;propertyId&#x60; field matches one or more values provided (optional)
     * @param  string[] $landlordId Only return transactions where the &#x60;landlordId&#x60; field matches one or more values provided (optional)
     * @param  string[] $tenancyId Only return transactions where the &#x60;tenancyId&#x60; field matches one or more values provided (optional)
     * @param  string[] $status Only return transactions where the &#x60;status&#x60; field matches one or more values provided (optional)
     * @param  string[] $type Only return transactions where the &#x60;type&#x60; field matches one or more values provided (optional)
     * @param  string[] $ledger Only return transactions where the &#x60;ledger&#x60; field matches one or more values provided (optional)
     * @param  string[] $category Only return transactions where the &#x60;category&#x60; field matches one or more values provided (optional)
     * @param  \DateTime $createdFrom Only return transactions where the &#x60;created&#x60; field is on or after the ISO8601 date and time value provided (optional)
     * @param  \DateTime $createdTo Only return transactions where the &#x60;created&#x60; field is on or before the ISO8601 date and time value provided (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transactionsGetAsyncWithHttpInfo($pageSize = null, $pageNumber = null, $sortBy = null, $id = null, $propertyId = null, $landlordId = null, $tenancyId = null, $status = null, $type = null, $ledger = null, $category = null, $createdFrom = null, $createdTo = null)
    {
        $returnType = '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20036';
        $request = $this->transactionsGetRequest($pageSize, $pageNumber, $sortBy, $id, $propertyId, $landlordId, $tenancyId, $status, $type, $ledger, $category, $createdFrom, $createdTo);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'transactionsGet'
     *
     * @param  int $pageSize A limit on the number of transactions to be returned per page. Value can range between 1 and 100, and the default is 25 (optional)
     * @param  int $pageNumber The page number to return (optional)
     * @param  string $sortBy Sort results by the value specified. Prefix string with &#39;-&#39; to indicate descending direction (created/modified) (optional)
     * @param  string[] $id Only return transactions where the &#x60;id&#x60; field matches one or more values provided (optional)
     * @param  string[] $propertyId Only return transactions where the &#x60;propertyId&#x60; field matches one or more values provided (optional)
     * @param  string[] $landlordId Only return transactions where the &#x60;landlordId&#x60; field matches one or more values provided (optional)
     * @param  string[] $tenancyId Only return transactions where the &#x60;tenancyId&#x60; field matches one or more values provided (optional)
     * @param  string[] $status Only return transactions where the &#x60;status&#x60; field matches one or more values provided (optional)
     * @param  string[] $type Only return transactions where the &#x60;type&#x60; field matches one or more values provided (optional)
     * @param  string[] $ledger Only return transactions where the &#x60;ledger&#x60; field matches one or more values provided (optional)
     * @param  string[] $category Only return transactions where the &#x60;category&#x60; field matches one or more values provided (optional)
     * @param  \DateTime $createdFrom Only return transactions where the &#x60;created&#x60; field is on or after the ISO8601 date and time value provided (optional)
     * @param  \DateTime $createdTo Only return transactions where the &#x60;created&#x60; field is on or before the ISO8601 date and time value provided (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function transactionsGetRequest($pageSize = null, $pageNumber = null, $sortBy = null, $id = null, $propertyId = null, $landlordId = null, $tenancyId = null, $status = null, $type = null, $ledger = null, $category = null, $createdFrom = null, $createdTo = null)
    {









        $resourcePath = '/transactions/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($pageSize)) {
            $pageSize = ObjectSerializer::serializeCollection($pageSize, '', true);
        }
        if ($pageSize !== null) {
            $queryParams['pageSize'] = $pageSize;
        }
        // query params
        if (is_array($pageNumber)) {
            $pageNumber = ObjectSerializer::serializeCollection($pageNumber, '', true);
        }
        if ($pageNumber !== null) {
            $queryParams['pageNumber'] = $pageNumber;
        }
        // query params
        if (is_array($sortBy)) {
            $sortBy = ObjectSerializer::serializeCollection($sortBy, '', true);
        }
        if ($sortBy !== null) {
            $queryParams['sortBy'] = $sortBy;
        }
        // query params
        if ($id !== null) {
            if('form' === 'form' && is_array($id)) {
                foreach($id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['id'] = $id;
            }
        }
        // query params
        if ($propertyId !== null) {
            if('form' === 'form' && is_array($propertyId)) {
                foreach($propertyId as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['propertyId'] = $propertyId;
            }
        }
        // query params
        if ($landlordId !== null) {
            if('form' === 'form' && is_array($landlordId)) {
                foreach($landlordId as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['landlordId'] = $landlordId;
            }
        }
        // query params
        if ($tenancyId !== null) {
            if('form' === 'form' && is_array($tenancyId)) {
                foreach($tenancyId as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['tenancyId'] = $tenancyId;
            }
        }
        // query params
        if ($status !== null) {
            if('form' === 'form' && is_array($status)) {
                foreach($status as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['status'] = $status;
            }
        }
        // query params
        if ($type !== null) {
            if('form' === 'form' && is_array($type)) {
                foreach($type as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['type'] = $type;
            }
        }
        // query params
        if ($ledger !== null) {
            if('form' === 'form' && is_array($ledger)) {
                foreach($ledger as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['ledger'] = $ledger;
            }
        }
        // query params
        if ($category !== null) {
            if('form' === 'form' && is_array($category)) {
                foreach($category as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['category'] = $category;
            }
        }
        // query params
        if (is_array($createdFrom)) {
            $createdFrom = ObjectSerializer::serializeCollection($createdFrom, '', true);
        }
        if ($createdFrom !== null) {
            $queryParams['createdFrom'] = $createdFrom;
        }
        // query params
        if (is_array($createdTo)) {
            $createdTo = ObjectSerializer::serializeCollection($createdTo, '', true);
        }
        if ($createdTo !== null) {
            $queryParams['createdTo'] = $createdTo;
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation transactionsIdGet
     *
     * Retrieves a specific transaction
     *
     * @param  string $id Unique identifier of the transaction to return (required)
     *
     * @throws \NorthernEstateAgencies\ReapitFoundationsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20036Embedded
     */
    public function transactionsIdGet($id)
    {
        list($response) = $this->transactionsIdGetWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation transactionsIdGetWithHttpInfo
     *
     * Retrieves a specific transaction
     *
     * @param  string $id Unique identifier of the transaction to return (required)
     *
     * @throws \NorthernEstateAgencies\ReapitFoundationsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20036Embedded, HTTP status code, HTTP response headers (array of strings)
     */
    public function transactionsIdGetWithHttpInfo($id)
    {
        $request = $this->transactionsIdGetRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20036Embedded' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20036Embedded', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20036Embedded';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20036Embedded',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation transactionsIdGetAsync
     *
     * Retrieves a specific transaction
     *
     * @param  string $id Unique identifier of the transaction to return (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transactionsIdGetAsync($id)
    {
        return $this->transactionsIdGetAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation transactionsIdGetAsyncWithHttpInfo
     *
     * Retrieves a specific transaction
     *
     * @param  string $id Unique identifier of the transaction to return (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transactionsIdGetAsyncWithHttpInfo($id)
    {
        $returnType = '\NorthernEstateAgencies\ReapitFoundationsClient\Model\InlineResponse20036Embedded';
        $request = $this->transactionsIdGetRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'transactionsIdGet'
     *
     * @param  string $id Unique identifier of the transaction to return (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function transactionsIdGetRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling transactionsIdGet'
            );
        }

        $resourcePath = '/transactions/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
